  apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: my-little-app
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          app: my-little-app
      spec:
        volumes:
          - name: spanner-creds
            secret:
              secretName: spanner-secret
        containers:
        - name: my-little-app
          image: gcr.io/onboarding-task/my-little-app:v1
          ports:
            - containerPort: 8080
              name: app
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /secrets/app-secrets/Onboarding Task-1f994c7276bc.json
          volumeMounts:
            - name: spanner-creds
              mountPath: /secrets/app-secrets
              readOnly: true
          imagePullPolicy: Always
  kind: Service
  apiVersion: v1
  metadata:
    name: my-little-app-load-balancer
  spec:
    selector:
      app: my-little-app
    ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
    type: LoadBalancer
    loadBalancerSourceRanges:
    - 151.140.0.0/16
    - 165.130.0.0/16
    - 207.11.0.0/17
    - 50.207.27.182/32
    - 98.6.11.8/29